import {test} from 'node:test';
import {strict as assert} from 'node:assert';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {intervals} from '@lapxo/obligations';
import {canonical,parse,wireAt} from '@lapxo/topos/wire';
import {semanticStandingBytes,readSemanticStanding} from '@lapxo/topos/standing';
import {unionReadings,snapshotIdentity,snapshotAccess,weightOf,composePolicy,renderWriter,originRegion,releaseSuccessors,checkCommandPort,commandRequest,commandResponse,foldedEvidence,vacuityOf,inspectionSelection} from '@lapxo/topos/contract';
import {boundOf} from '../src/wire/values.ts';

const read=(relative:string)=>JSON.parse(readFileSync(new URL(relative,import.meta.url),'utf8'));
const digest=(bytes:string)=>'sha256:'+createHash('sha256').update(bytes).digest('hex');
test('the published readings vector is verified, never regenerated by tests',()=>{
  const sample=read('../samples/readings/yes.json'),vector=read('../vectors/readings.json');
  const output=sample.places.map((place:{name:string;sign:string;join:string;readings:string[];source:string;content:string;clock:string;observed:string;implementation:string})=>{
    const mark=(id:string,value:string,reach:string)=>canonical({type:'mark',id,cell:place.name,sign:'+1',pole:'ceiling',reach,value,...(reach==='local'?{widens:'w'}:{})});
    const sign=mark('s',place.sign,'travels'),join=mark('j',place.join,'local');
    const readings=place.readings.map((value,index)=>({world:'world-'+index,region:place.name,
      lines:[canonical({scope:'reading/'+place.name,role:'writes',form:'interval',measure:'span',value,origin:'source-'+index})]}));
    const union=unionReadings(readings),duplicate=unionReadings([...readings,...readings]);
    const origins=(lines:readonly string[])=>new Set(lines.map(line=>{const p=parse(line);return p.kind==='fact'?p.value.fields.origin:undefined;})).size;
    const snapshot={source:place.source,content:place.content,clock:place.clock,observed:place.observed,implementation:place.implementation};
    const context={principal:'principal',authorization:'grant',implementation:place.implementation,snapshot:snapshotIdentity(snapshot,digest),request:'request'};
    const lattice=intervals(0,100);
    const field={coordinate:place.name,mode:'meet' as const,lattice,inhabited:lattice.inhabited,decode:(value:string)=>{
      const bound=boundOf('interval',value);if(!bound||bound.kind!=='interval'||bound.lo===null||bound.hi===null)throw Error('invalid fixture interval');return {lo:bound.lo,hi:bound.hi};
    }};
    const origin=originRegion([canonical({scope:'region/'+place.name,role:'writes',measure:'origin',value:place.source})],'region/'+place.name);
    const withdrawn=canonical({scope:'reading/'+place.name,role:'writes',measure:'span',value:'withdraw'});
    const evidence=foldedEvidence([readings[0]!.lines[0]!,withdrawn],{classification:()=> 'local',fold:lines=>lines});
    const port={coordinate:'port/'+place.name,implementation:place.implementation,closure:[place.implementation],timeoutMs:1000,responseBytes:4096,environment:[],stderr:'reject' as const};
    const lot={identity:place.content,requests:place.readings};
    checkCommandPort(port,{admitsDeclaration:()=>true,covers:coordinate=>coordinate===port.coordinate,verifies:value=>value===place.implementation});
    const frame=JSON.parse(commandRequest(port,lot));
    const stdout=JSON.stringify({...frame,responses:frame.requests.map(()=> 'accepted')})+'\n';
    const successors=releaseSuccessors(place.content,[{digest:place.implementation,predecessor:place.content},{digest:digest(place.name),predecessor:place.content}],()=>true);
    return {place:place.name,projectionOrderDistinct:digest(semanticStandingBytes([sign,join]))!==digest(semanticStandingBytes([join,sign])),
      worldPermutationEqual:JSON.stringify(union)===JSON.stringify(unionReadings([...readings].reverse())),
      duplicateOriginAdded:origins(duplicate.lines)>origins(union.lines),incompatibleValuesRetained:union.disagreements[0]!.lines.length,
      unknownFreshnessReuse:snapshotAccess(snapshot,context,context,{inspect:true,reuse:true,freshness:'unknown'},digest).reuse,
      missingScan:weightOf([],false).total,emptyMeet:composePolicy(field,place.readings.map((value,index)=>({source:String(index),own:index===1,value}))).kind,
      originResolved:origin?.source===place.source,historyKept:evidence.history.length,standingLive:evidence.standing.length,
      completeLot:commandResponse(port,lot,{status:0,interrupted:false,stdout,stderr:''},member=>member==='accepted'),
      successorsKept:successors.length,selectionKept:inspectionSelection([place.name,place.name],[place.name]).length,
      knownBytes:weightOf([{digest:place.content,bytes:12,named:true},{digest:place.implementation,bytes:7,named:false}],true).total,
      vacuity:vacuityOf(Number(place.observed),3,[],false).reading};
  });
  assert.deepEqual(output,vector.output);
});

test('published counterexamples preserve refusal, incompatibility and unknown',()=>{
  const cases=read('../samples/readings/no.json').cases;
  for(const sample of cases){
    const run=()=>{
      switch(sample.kind){
        case 'projection':return semanticStandingBytes(sample.lines);
        case 'projection-bytes':return readSemanticStanding(sample.bytes);
        case 'writer':return renderWriter(sample.coordinate,sample.writers);
        case 'origin':return originRegion(sample.lines,sample.coordinate);
        case 'lineage':return releaseSuccessors(sample.current,sample.links,()=>true);
        case 'weight':return weightOf(sample.entries,true);
        case 'wire':return wireAt(sample.lines,sample.epoch);
        case 'port':return checkCommandPort(sample.port,{admitsDeclaration:()=>sample.admitted,covers:()=>sample.covered,verifies:()=>sample.verified});
        case 'policy': {
          const lattice=intervals(0,100);
          return composePolicy({coordinate:sample.coordinate,mode:'meet',lattice,inhabited:lattice.inhabited,decode:value=>{
            const bound=boundOf('interval',value);
            if(!bound||bound.kind!=='interval'||bound.lo===null||bound.hi===null)throw Error('invalid sample interval');
            return {lo:bound.lo,hi:bound.hi};
          }},sample.values.map((value:string,index:number)=>({source:String(index),own:index===1,value}))).kind;
        }
        case 'snapshot-access': {
          const context={...sample.context,snapshot:snapshotIdentity(sample.snapshot,digest)};
          return snapshotAccess(sample.snapshot,context,{...context,...sample.changes},
            {inspect:true,reuse:true,freshness:sample.freshness??'fresh'},digest);
        }
        case 'evidence':return foldedEvidence(sample.history,{classification:()=> 'local',fold:()=>sample.folded});
        case 'vacuity':return vacuityOf(sample.now,sample.window,sample.epochs,sample.complete).reading;
        case 'inspection':return inspectionSelection(sample.selection,sample.admitted);
        case 'response':return commandResponse(sample.port,sample.lot,sample.execution,()=>true);
        default:throw Error('unknown negative fixture');
      }
    };
    if(sample.error)assert.throws(run,error=>error instanceof Error&&error.message.startsWith(sample.error));
    else assert.deepEqual(run(),sample.expected);
  }
});
