import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHash,generateKeyPairSync,sign,verify} from 'node:crypto';
import {canonical,parse,signedBytes,formatSignature,parseSignature} from '../src/wire/index.ts';
import {walkSelection,walkSnapshot,walkInventory,walkAt,walkPayload,walkHeaders,readForeignWalk} from '../src/walk.ts';
import {readFileSync} from 'node:fs';
const declarations=JSON.parse(readFileSync(new URL('../samples/walk/refinement.json',import.meta.url),'utf8'));
const contract=walkSelection(declarations);
const digest=(bytes:string)=>'sha256:'+createHash('sha256').update(bytes).digest('hex');
const pair=generateKeyPairSync('ed25519');
const signed=(f:Record<string,string>)=>canonical({...f,sig:formatSignature('ed25519:sample',sign(null,Buffer.from(signedBytes(f)),pair.privateKey).toString('base64'))});
const line=(scope:string,value:string,epoch='1')=>signed({scope,value,epoch,by:'writer',at:'origin:sample',role:'reads',form:'alphabet',measure:'id'});
const authenticate=(lines:readonly string[])=>lines.every(line=>{const p=parse(line);if(p.kind!=='fact')return false;const f=p.value.fields,sig=parseSignature(f.sig!);return Boolean(sig&&verify(null,Buffer.from(signedBytes(f)),pair.publicKey,Buffer.from(sig.raw,'base64')))});
for(const family of ['reading','artifact'])test('declared coordinate refinement grows with history: '+family,()=>{
 const a=line(family+'/north/first','one'),b=line(family+'/south/second','kept'),disagreement=line(family+'/north/first','other','2'),c=line(family+'/north/third','new','2');
 const peer=walkSnapshot([a,b],contract.fields,digest,'opaque/origin',contract.partition);
 const own=walkSnapshot([a,b,disagreement,c],contract.fields,digest,'opaque/origin',contract.partition);
 assert.equal(own.regions.length,3);assert.equal(own.refinements!.find(r=>r.depth===1)!.regions.length,1);assert.equal(own.refinements!.find(r=>r.depth===2)!.regions.length,2);
 const coarse=walkAt(own,peer,0,contract.projections),medium=walkAt(own,peer,4,contract.projections),fine=walkAt(own,peer,6,contract.projections);
 assert.equal(coarse.root,medium.root);assert.equal(medium.root,fine.root,'detail does not replace history identity');assert.equal(coarse.regions.length,1);assert.equal(medium.regions.length,1,'only the changed northern group is open');assert.equal(fine.regions.length,2,'unchanged leaf is reused');assert.ok(fine.records.includes(a)&&fine.records.includes(disagreement)&&fine.records.includes(c));assert.ok(!fine.records.includes(b));
 const ack=walkInventory([peer.regions],digest,contract.partition);
 assert.deepEqual(walkAt(own,ack,6,contract.projections),fine,'verified inventory needs no provider records to refine');
 const coarsePeer=walkAt(peer,{root:'',regions:[]},0,contract.projections);const same=walkAt(peer,coarsePeer,6,contract.projections);assert.equal(same.records.length,0,'an equal coarse commitment covers its complete children');
 const packets=walkPayload(fine.records,fine.regions,contract.fields,digest,authenticate,'opaque/origin',contract.partition);assert.deepEqual(packets,fine.records);
 assert.throws(()=>walkPayload(fine.records.slice(1),fine.regions,contract.fields,digest,authenticate,'opaque/origin',contract.partition),/REFUSE·walk/);
 assert.throws(()=>walkPayload(fine.records,medium.regions,contract.fields,digest,authenticate,'opaque/origin',contract.partition),/REFUSE·walk/,'a group digest proves no arbitrary record fragment');
 const headers=walkHeaders(fine,'sha256:context','base',true).map(l=>{const p=parse(l);assert.equal(p.kind,'fact');return signed({...p.value.fields,by:'writer',epoch:'2'})});
 const proof={origin:'opaque/origin',regionOrigin:'opaque/origin',partition:contract.partition,context:'sha256:context',base:'base',fields:contract.fields,digest,previousPrefixes:[],authenticatePrefix:authenticate,authenticateEvidence:authenticate,validateOriginHistory:()=>true};
 assert.deepEqual(readForeignWalk([...headers,...fine.records],proof).records,fine.records);
 const previous=peer.regions.filter(r=>r.scope.endsWith('/first')).map(r=>({...r,senderEpoch:1}));
 const removed=walkSnapshot([disagreement],contract.fields,digest,'opaque/origin',contract.partition),removedPacket=walkAt(removed,{root:'',regions:[]},6,contract.projections);const removedHeaders=walkHeaders(removedPacket,'sha256:context','base',true).map(l=>signed({...parse(l).value.fields,by:'writer',epoch:'2'}));
 assert.throws(()=>readForeignWalk([...removedHeaders,...removedPacket.records],{...proof,previousPrefixes:previous}),/not an extension/,'refinement keeps the origin prefix guard');
});
test('refinement must be declared completely; history cannot carry grouped fragments',()=>{
 const replace=(scope:string,value:string)=>declarations.map((l:string)=>{const p=parse(l);return p.value.fields.scope===scope?canonical({...p.value.fields,value}):l});
 const no=JSON.parse(readFileSync(new URL('../samples/walk/refinement.no.json',import.meta.url),'utf8'));
 assert.throws(()=>walkSelection(no),/history requires complete/);
 assert.throws(()=>walkSelection(replace('wire/walk/refinements','0:1|1:1|4:2|6:all')),/does not match/);
 assert.throws(()=>walkSelection(replace('wire/walk/partition','guessed')),/unsupported coordinate partition/);
 assert.throws(()=>walkSnapshot([line('reading/x','one')],contract.fields,digest,undefined,contract.partition),/requires a declared origin/);
 assert.throws(()=>walkAt(walkSnapshot([],contract.fields,digest,'origin'),{root:'',regions:[]},4,contract.projections),/matching snapshot partition/);
 assert.throws(()=>walkInventory([[{scope:'receipts/origin/reading',digest:digest('x'),count:-1}]],digest,contract.partition),/invalid inventory count/);
});
